export const locatorsXpath = {
    "cookieAccept": "//div[@class = 'AgreementCookie_buttons__zhpxj']//button[2]",
    "account": "//div//button/span[contains(text(), 'Аккаунт')]",
    "registration": "//*[@id='modal']//button[2]",
    "login": "//div//button/div/span[contains(text(), 'Войти')]",
    "basket": "//div//a/div[contains(text(), 'Корзина')]",
    "favorites": "//div//a/div[contains(text(), 'Избранные товары')]",
    "comparisonList": "//div//a/div[contains(text(), 'Списки')]",
    "watched": "//div//a/div[contains(text(), 'Просмотренные')]",
    "email": "//div//label[contains(text(), 'Электронная')]",
    "password": "//div//label[contains(text(), 'Пароль')]",
    "forgetPassword": "//div//button[contains(text(), 'Забыли пароль')]",
    "enterInPopUp": "//div//button[1]/div[contains(text(), 'Войти')]",
    "registrationEmailInput": "//div//input[@id='register-email']",
    "continueButton": "//div//button/div[contains(text(), 'Продолжить')]",
    "validationEmailNotSpecified": "//div//span[contains(text(), 'Электронная почта')]",
    "validationNotCorrectEmail": "//div//span[contains(text(), 'Неправильный формат')]",
    "agementProcessing": "//div//button[2]/div",
    "disagrementProcessing": "//div//button[1]/div[contains(text(), 'Отказываюсь')]",
    "rulesProcessing": "//div//a[contains(text(), 'правами, механизмом их реализации')]",
    "emailValidation" : "//div//form/div/div[1]/div[3]//span[2]", 
    "emailValidationSecond" : "//div[@id='modal']//span//span[contains(text(), 'Проверьте электронную почту')]", 
    "passwordValidation" : "//div//form/div/div[2]/div[3]/span[2]/span[contains(text(), 'Неправильный пароль')]",
    "passwordValidationSecond" : "//div[@id='modal']//span[contains(text(),'Неправильный пароль. ')]",
    "congratulations" : "//div//h5[contains(text(), 'Вы зарегистрированы')]",
    "rules" : "//*[@id='page_header']",
    "notFound" : "//div[@id='j-paginator']/span",
    "iphone" : "//div//span[contains(text(), 'iPhone 13 128GB (темная ночь)')]"
  };

